apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- csi-controller.yaml
- csi-node.yaml
- mutatingwebhooks.yaml
- namespace.yaml
- provisioner.yaml
- psp.yaml
- scheduler.yaml
