kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  # When update to Kubernetes 1.15, make sure to change the
  # apiVersion to "kubeadm.k8s.io/v1beta2".  Also make sure
  # to change the node image in Makefile (--image kindest/node)
  apiVersion: kubeadm.k8s.io/v1beta1
  kind: ClusterConfiguration
  metadata:
    name: config
  kubernetesVersion: "v@KUBERNETES_VERSION@"
  networking:
    serviceSubnet: 10.0.0.0/16
  scheduler:
    extraVolumes:
      - name: "config"
        hostPath: /mnt/host/scheduler
        mountPath: /var/lib/scheduler
        readOnly: true
    extraArgs:
      config: /var/lib/scheduler/scheduler-config.yaml
nodes:
- role: control-plane
  extraMounts:
    - containerPath: /mnt/host/scheduler
      hostPath: /tmp/topolvm/scheduler
    - containerPath: /var/lib/kubelet
      hostPath: /tmp/topolvm/controller
      propagation: Bidirectional
- role: worker
  extraMounts:
    - containerPath: /run/topolvm
      hostPath: /tmp/topolvm/lvmd
    - containerPath: /var/lib/kubelet
      hostPath: /tmp/topolvm/worker
      propagation: Bidirectional
