apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../deploy/manifests
patches:
  - mutatingwebhooks.yaml
  - controller.yaml
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml
secretGenerator:
- name: mutatingwebhook
  namespace: topolvm-system
  files:
  - ca.crt=./build/certs/ca.pem
  - tls.crt=./build/certs/server.pem
  - tls.key=./build/certs/server-key.pem
  type: "Opaque"
vars:
  - name: TLSCERT
    objref:
      kind: Secret
      version: v1
      name: mutatingwebhook
    fieldref:
      fieldpath: data[ca.crt]
