apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: topolvm-hook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-system:topolvm-hook
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-system:topolvm-hook
subjects:
  - kind: ServiceAccount
    name: topolvm-hook
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-system:topolvm-hook
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: topolvm-hook
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: topolvm-hook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: topolvm-hook
    spec:
      serviceAccountName: topolvm-hook
      containers:
        - name: topolvm-hook
          image: topolvm:dev
          imagePullPolicy: Never
          command:
            - /topolvm-hook
            - --listen=:9252
            - --cert=/certs/server.pem
            - --key=/certs/server-key.pem
          livenessProbe:
            httpGet:
              path: /status
              port: 9252
              scheme: HTTPS
          volumeMounts:
            - name: server-certs
              mountPath: /certs
      hostNetwork: true
      volumes:
        - name: server-certs
          secret:
            secretName: topolvm-hook-certs
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: topolvm-hook
  labels:
    app.kubernetes.io/name: topolvm-hook
webhooks:
  - name: hook.topolvm.cybozu.com
    clientConfig:
      url: https://localhost:9252/mutate
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZRENDQWtpZ0F3SUJBZ0lVQWFIeGhBUEhLVkRQL05Id1VnZzVYNmhuY25Bd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1NERUxNQWtHQTFVRUJoTUNTbEF4RVRBUEJnTlZCQWdUQ0VOb2RXOW9MV3QxTVE0d0RBWURWUVFIRXdWVQpiMnQ1YnpFV01CUUdBMVVFQXhNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweE9UQTJNVEl3T0RRek1EQmFGdzB5Ck5EQTJNVEF3T0RRek1EQmFNRWd4Q3pBSkJnTlZCQVlUQWtwUU1SRXdEd1lEVlFRSUV3aERhSFZ2YUMxcmRURU8KTUF3R0ExVUVCeE1GVkc5cmVXOHhGakFVQmdOVkJBTVREV05zZFhOMFpYSXViRzlqWVd3d2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEWk1CY3NHK2FuclhwdDRUaDJ2SkRZVlRZVzhibTdERThkCm9IK2t6R3BIOVVVRkl0LzFrbDgyem9laWVhMWYwSGVZS004Wk94WFdQNjRDN0Vaam9yYXM3RWNFNjBJM1M1ZlUKK25QV2E3aUQvSzNDUzUvZmtCTVNZZTdhOXZPaHdpYVo4T1hmY00zbm11SStVbGVUUGhQanJKU2xHTCtDY0wzYQp3OE1KcmRsQzFaQVZSNnkrS3p6c3c1Tnl5cUp5OE1iY0pLcVN3M09sY25wbGFHSjA5K01Sc0s0dlMzSEx5UjFjClNzU2NWL3pEWWF1RHppV3RuNXA5MVh6Nzg2RWx5enk5Y0xCTnFTNDFNUWE1TGlDWEE1eERUVkZRUzVtcVBZUDUKZU1XZ2tDUmdGNlhOVHBvenpFdVdKcWxiNDhxVmo0ckFranhBUmZXdVVVZ0k3YmtnWW1xWEFnTUJBQUdqUWpCQQpNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCVFUraWQzClh6eW5hYkllMGVxWER4UU1BNEdLTnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWJza0NzVVFHaTZobUNXN1cKNEN2U3NlZXgvSUNCQnh1bEdXRFh1aENpQU9xYi9qVTl3dTgyVW9qbkNuVjB1NHY1bEtMTzMwVGREbEtLQzVyTgpFTzZsZWFqcFBYRHNvY2EyanBNT1hSd3gxM2RlSWRpaG5VbE9NejE1cERxcFBvWU14QzlsQXUzTGwrZk5QTm9sCmNKb004bkw0TDhraTNlTTc5NjkwZGZKenpubWJnb1JRbG5Fd01GL1dKTnAvZUVBUENHM0cyTWg4b01kNE9WeDMKc2hrckY0QWQzSlBRY3M1T0lWdjZZMWNybi9vd29XN2MxTkNLRHpNeU5zUndwejcydXVmV2FvdmZMS09FTWZ5egpIUCt4NVUvU3dSVlY1NGtkNW9BR0pwN0NGYUVxcFl4U2pIVXRBNFpmWWE3dmo3MExlMGR2NzM1YkFoVGNjVFFPCmR5UXNIQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
