apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: topolvm-system
  name: lvmetrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topolvm-system:lvmetrics
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: topolvm-system:lvmetrics
subjects:
- kind: ServiceAccount
  name: lvmetrics
  namespace: topolvm-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: topolvm-system:lvmetrics
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lvmetrics
  namespace: topolvm-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lvmetrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lvmetrics
    spec:
      serviceAccountName: lvmetrics
      containers:
        - name: lvmetrics
          image: topolvm:dev
          imagePullPolicy: Never
          command:
            - /lvmetrics
            - --socket=/tmp/lvmd.sock
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
          - name: topolvm-volume
            mountPath: /tmp
      volumes:
      - name: topolvm-volume
        hostPath:
          path: /tmp/topolvm
