apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scheduler-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scheduler-role-binding
  namespace: kube-system
subjects:
  - kind: User
    name: system:kube-scheduler
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scheduler-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: topolvm-system
  name: topolvm-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: topolvm-system:topolvm-scheduler
  namespace: topolvm-system
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: topolvm-system:topolvm-scheduler
  namespace: topolvm-system
subjects:
  - kind: ServiceAccount
    name: topolvm-scheduler
    namespace: topolvm-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: topolvm-system:topolvm-scheduler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topolvm-scheduler
  namespace: topolvm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: topolvm-scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: topolvm-scheduler
    spec:
      serviceAccountName: topolvm-scheduler
      containers:
        - name: topolvm-scheduler
          image: topolvm:dev
          imagePullPolicy: Never
          command:
            - /topolvm-scheduler
            - --listen=:9251
            - --divisor=1
            - --spare=1
          livenessProbe:
            httpGet:
              path: /status
              port: 9251
---
apiVersion: v1
kind: Service
metadata:
  name: topolvm-scheduler
  namespace: topolvm-system
spec:
  selector:
    app.kubernetes.io/name: topolvm-scheduler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9251

