kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta1
  kind: ClusterConfiguration
  metadata:
    name: config
  networking:
    serviceSubnet: 10.0.0.0/16
  scheduler:
    extraVolumes:
      - name: "config"
        hostPath: /mnt/host/scheduler-config.yaml
        mountPath: /var/lib/scheduler/scheduler-config.yaml
        readOnly: true
        pathType: File
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
  extraMounts:
    - containerPath: /mnt/host/scheduler-config.yaml
      hostPath: /home/ikezoe/go/src/github.com/cybozu-go/topolvm/kindtest/scheduler-config.yaml
# the three workers
- role: worker
  extraMounts:
    - containerPath: /tmp/topolvm
      hostPath: /tmp/topolvm
- role: worker
  extraMounts:
    - containerPath: /tmp/topolvm
      hostPath: /tmp/topolvm
- role: worker
  extraMounts:
    - containerPath: /tmp/topolvm
      hostPath: /tmp/topolvm
