
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /pvc/mutate
  failurePolicy: Fail
  name: pvc-hook.topolvm.cybozu.com
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - persistentvolumeclaims
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /pod/mutate
  failurePolicy: Fail
  name: pod-hook.topolvm.cybozu.com
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
