name: Lint and Test Charts

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  lint-test:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.0

      - name: Setup helm-docs
        run: |
          HELM_DOCS_VERSION="1.5.0"
          OS=$(uname)

          curl -L -sS https://github.com/norwoodj/helm-docs/releases/download/v"${HELM_DOCS_VERSION}"/helm-docs_"${HELM_DOCS_VERSION}"_${OS}_x86_64.tar.gz \
            | tar zx -C /tmp
          sudo mv /tmp/helm-docs /usr/local/bin

      - name: Run helm-docs
        run: helm-docs && git diff --no-patch --exit-code

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      - name: Setup kind
        run: |
          make -C e2e setup
          make -C e2e daemonset-lvmd/create-vg
          make -C e2e daemonset-lvmd/setup-minikube
          make -C e2e daemonset-lvmd/update-minikube-setting
          make -C e2e topolvm.img
          sudo chown -R "$USER" "$HOME/.kube" "$HOME/.minikube"

      - name: Apply cert-manager CRDs
        run: kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.3.1/cert-manager.crds.yaml

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml
