apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../e2ebase
patchesJson6902:
- target:
    group: storage.k8s.io
    version: v1beta1
    kind: CSIDriver
    name: topolvm.cybozu.com
  path: controller.yaml
- target:
    group: storage.k8s.io
    version: v1
    kind: StorageClass
    name: topolvm-provisioner
  path: provisioner.yaml
