apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: topolvm-system
  name: csi-topolvm-node
spec:
  template:
    spec:
      containers:
        - name: node
          image: topolvm:dev
          imagePullPolicy: Never
          volumeMounts:
            - name: device-dir
              mountPath: /dev

        - name: csi-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
          imagePullPolicy: "IfNotPresent"
          command:
            - /csi-node-driver-registrar
            - "--csi-address=/run/topolvm/csi-topolvm.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/topolvm.cybozu.com/node/csi-topolvm.sock"

        - name: topolvm-node
          image: topolvm:dev
          imagePullPolicy: Never
          command:
            - /topolvm-node
            - --node-name=$(MY_NODE_NAME)
            - --lvmd-socket=/run/lvmd/lvmd.sock
            - --development=true

        - name: lvmetrics
          image: topolvm:dev
          imagePullPolicy: Never

      volumes:
        - name: lvmd-socket-dir
          hostPath:
            path: /tmp/topolvm
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
